apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "changeimage.fullname" . }}-write
  labels:
    {{- include "changeimage.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  - certificates.k8s.io
  - ""
  resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    - certificatesigningrequests
    - certificatesigningrequests/approval
    - certificatesigningrequests/status
    - signers
    - namespaces
  verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
    - approve
    - sign
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "changeimage.fullname" . }}-read
  labels:
    {{- include "changeimage.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - pg.io
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - poddisable
  - implicitimagerules
  - explicitimagerules
  - defaultimagerules
  verbs:
  - get
  - list
  - watch
