apiVersion: v1
data:
  config.py: |
    bind = ":{{ .Values.webhook.webhookServicePort }}"
    workers = 2
    threads = 2
    certfile = "{{ .Values.webhook.webhookSecretFsPath }}/cert.pem"
    keyfile = "{{ .Values.webhook.webhookSecretFsPath }}/key.pem"
  labels: |
    namespace: {{ .Release.Namespace }}
    {{- include "changeimage.labels" . | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ include "changeimage.fullname" . }}
  namespace: {{ .Release.Namespace }}
