apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    {{- include "changeimage.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
  name: {{ include "changeimage.fullname" . }}-mwc
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "changeimage.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: {{ .Values.webhook.webhookWorkloadPath }}
      port: {{ .Values.service.port }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: {{ .Values.webhook.webhookName }}
  namespaceSelector:
    matchLabels:
      {{ .Values.webhook.webhookLabel }}: enabled
  objectSelector: {}
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - deployments
    - daemonsets
    - statefulsets
    scope: '*'
  sideEffects: None
  timeoutSeconds: 20
