apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "changeimage.fullname" . }}
value: 1000  # Higher value means higher priority
globalDefault: false
description: "This priority is for changeimage MW."
