apiVersion: v1
kind: Service
metadata:
  name: {{ include "changeimage.fullname" . }}
  labels:
    {{- include "changeimage.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "changeimage.selectorLabels" . | nindent 4 }}
